---
- name: Create Let's Encrypt directories
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: root
    group: wheel
    mode: "{{ item.mode }}"
  with_items:
    - { dir: "/etc/ssl/letsencrypt/connectbox.org", mode: "0755" }
    - { dir: "/etc/ssl/letsencrypt/private/connectbox.org", mode: "0700" }
    - { dir: "/etc/letsencrypt/connectbox.org", mode: "0700" }

#       Also need to add a crontab entry to renew the certificate.
#       See acme-client(1) for an example

- name: Copy LE certs to allow nginx to start
  copy:
    src: "{{ item.src }}"
    dest: "/etc/ssl/letsencrypt/{{ item.dest }}"
    force: no
    owner: root
    group: wheel
    mode: 444
  with_items:
    - { src: /Users/esteele/Code/local/letsencrypt/connectbox.org/cert.pem, dest: connectbox.org/cert.pem }
    - { src: /Users/esteele/Code/local/letsencrypt/connectbox.org/chain.pem, dest: connectbox.org/chain.pem }
    - { src: /Users/esteele/Code/local/letsencrypt/connectbox.org/fullchain.pem, dest: connectbox.org/fullchain.pem }

- name: Copy LE domain privkeys to allow nginx to start
  copy:
    src: "{{ item.src }}"
    dest: "/etc/ssl/letsencrypt/private/{{ item.dest }}"
    force: no
    owner: root
    group: wheel
    mode: 400
  with_items:
    - { src: /Users/esteele/Code/local/letsencrypt/connectbox.org/private/domain-privkey.pem, dest: connectbox.org/privkey.pem }

- name: Copy LE account privkey to allow certificate renewals
  copy:
    src: "{{ item.src }}"
    dest: "/etc/letsencrypt/{{ item.dest }}"
    force: no
    owner: root
    group: wheel
    mode: 400
  with_items:
    - { src: /Users/esteele/Code/local/letsencrypt/connectbox.org/private/account-privkey.pem, dest: connectbox.org/privkey.pem }


# Are these challenge directories even needed given the location blocks in vhosts.conf?
- name: Setup webserver parent and acme-client challenge directories
  file:
    path: "/var/www/htdocs/{{ item }}"
    state: directory
    owner: esteele
    group: esteele
    mode: 0755
  with_items:
    - demo.connectbox.org
    - demo.connectbox.org/.well-known/acme-client

# Set USER in environment because of doas + git (see nikola/tasks/main.yml
#  for a full explanation)
#- block:
#  - name: Clone connectbox repo
#    git:
#      repo: https://github.com/ConnectBox/connectbox-pi.git
#      dest: "{{ connectbox_pi_repo_location }}"

#  - name: Checkout sample content
#    git:
#      repo: https://github.com/ConnectBox/connectbox-sample-content.git
#      dest: "{{ connectbox_sample_content_repo_location }}"

#  - name: Symlink readme for demo site
#    file:
#      src: "../README - demo site.txt"
#      dest: "{{ connectbox_sample_content_repo_location }}/content/README - demo site.txt"
#      state: link

#  become: True
#  become_method: doas
#  become_user: esteele
#  environment:
#    USER: esteele

#- name: Schedule periodic update of connectbox repos
#  cron:
#    name: Update web connectbox repos
#    special_time: hourly
#    user: esteele
#    job: "git -C {{ connectbox_pi_repo_location }} pull; git -C {{ connectbox_sample_content_repo_location }} pull"

- name: Configure nginx for connectbox.org
  include_role:
    name: geerlingguy.nginx
  vars:
    nginx_vhosts_filename: "{{ connectbox_org_vhosts_filename }}"
    nginx_vhosts: "{{ connectbox_org_nginx_vhosts }}"
