---
- name: Restart smb
  ansible.builtin.service:
    name: smb
    state: restarted

- name: Restart avahi-daemon
  ansible.builtin.service:
    name: avahi-daemon
    state: restarted

- name: Reload udev rules
  ansible.builtin.command: udevadm control --reload-rules
  become: true

- name: Restart smartd
  ansible.builtin.service:
    name: smartd
    state: restarted
