---
- name: Create base directory for random parameter
  file: path=/etc/ssl/certs/misc owner=root group=wheel state=directory

- name: Generate 2048bit random parameter for nginx DH Elliptic Curves
  command: openssl dhparam -outform pem -out /etc/ssl/certs/misc/nginx-dhparam2048.pem 2048
           creates=/etc/ssl/certs/misc/nginx-dhparam2048.pem

# Stop httpd first, so we don't have port clashes
- name: Set httpd to not auto-start and stop if running
  service: name=httpd enabled=no state=stopped
