---
- name: Allow travis to push staging web assets
  authorized_key:
    user: esteele
    state: present
    key_options: command="rsync --server -vlogDtpr --delete . /home/esteele/Sites/{{ item.site }}/"
    key: "ssh-rsa {{ item.key }}"
  with_items:
    - { site: staging.wordspeak.org,
        key: AAAAB3NzaC1yc2EAAAADAQABAAABAQCbsvzantF5jM8bXd7DSJCNaDWWoMWyDDnfOMiXhkKSrPxYzuM643gX1wEiw1ywR3GvE2v2B9s4R9s4hxeuoXNx8CN1Zn5T2If5pjloD0YEVdz2KrrtIbjyCMtb+z9c4P6b6CTjJwaIm8Q364lzVwA02r8wNsgY43fKJwMArhKyzf1tXLTwknJQfhwzLepAKGWC5utDI25iuaRnUPGaMBRpZ93iLg+YOlaXmGG8hg6L7pL5MqmutM7zrCII2FKLaLEGCj9gYA2ML6JG3dovVNUlqvnJ+GHWCZoYUt36QyEEywSWpRudS8yupnUhEOl7PPNDUNn4OwgFxalcWy15HBmD }  # noqa 204
    - { site: www.wordspeak.org,
        key: AAAAB3NzaC1yc2EAAAADAQABAAABAQDKycXLuWGG0t6f37n755PIW+/Usk3RK85nTKmp7XInK3z5SIUBCvhj7MplkyiFd48oz/jenppFGqKrKr0Pbzw1jGTTM3C1xZVyvB4b56YJr49ZPDrfWtSaXJe9zismbGpZKTRJtpjLE2gg44QD7AFqB8IbXCCUeZ/P9y7on7UoTEYHR+SlaKnQ28DSRUdWQa2f5sM7KcWHVHNwAUDagidRv2OuHo0UE8n8ovpgc3uGfQs1Y8HH+XCxxUOnV+oW32gUW9t2mEZ1yn00oILjUHuV6myJiqnUmMSkn494lxJIfTgHhY3bexnb/Hkh2Wibnk4ylQAsnoEKdKGsIsEVY7ST }  # noqa 204
