---
- name: setup pf.conf for this role
  copy: src=pf_conf dest=/etc/pf.conf
        owner=root group=wheel mode=0600
        validate="pfctl -n -f %s"
  register: pf_conf_changed

- name: apply any new pf rules immediately
  command: pfctl -f /etc/pf.conf
  when: pf_conf_changed["changed"]

- include: base_nginx.yml

- name: Setup ~esteele/Sites, allowing it to be served up
  file: dest=/home/esteele/Sites state=directory
        owner=esteele group=esteele mode=0711

- name: Create Let's Encrypt directories
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: root
    group: wheel
    mode: "{{ item.mode }}"
  with_items:
    - { dir: "/var/www/letsencrypt", mode: "0755" }
    - { dir: "/etc/ssl/letsencrypt", mode: "0755" }
    - { dir: "/etc/ssl/letsencrypt/private", mode: "0700" }

#       Also need to add a crontab entry to renew the certificate.
#       See acme-client(1) for an example

- name: Copy LE certs to allow nginx to start
  copy:
    src: "{{ item.src }}"
    dest: "/etc/ssl/letsencrypt/{{ item.dest }}"
    force: no
    owner: root
    group: wheel
    mode: 444
  with_items:
    - { src: /Users/esteele/Code/local/letsencrypt/cert.pem, dest: cert.pem }
    - { src: /Users/esteele/Code/local/letsencrypt/chain.pem, dest: chain.pem }
    - { src: /Users/esteele/Code/local/letsencrypt/fullchain.pem, dest: fullchain.pem }

- name: Copy LE certs to allow nginx to start
  copy:
    src: /Users/esteele/Code/local/letsencrypt/privkey.pem
    dest: /etc/ssl/letsencrypt/private/privkey.pem
    force: no
    owner: root
    group: wheel
    mode: 400

- name: Setup webserver parent and acme-client challenge directories
  file: path=/var/www/htdocs/{{ item }} state=directory
        mode=0755 owner=esteele group=esteele
  with_items:
    - staging.wordspeak.org
    - www.wordspeak.org
    - language-explorer.wordspeak.org
    - staging.wordspeak.org/.well-known/acme-client
    - www.wordspeak.org/.well-known/acme-client
    - language-explorer.wordspeak.org/.well-known/acme-client

- name: Setup staging.wordspeak.org symlink
  file: dest=/home/esteele/Sites/staging.wordspeak.org
        src=/var/www/htdocs/staging.wordspeak.org
        state=link

- name: Setup language-explorer.wordspeak.org symlink
  file: dest=/home/esteele/Sites/language-explorer.wordspeak.org
        src=/var/www/htdocs/language-explorer.wordspeak.org
        state=link

- name: Setup www.wordspeak.org symlink
  file: dest=/home/esteele/Sites/www.wordspeak.org
        src=/var/www/htdocs/www.wordspeak.org
        state=link

- include: nikola.yml
