---
- name: Copy wordspeak deploy key
  copy: src=/Users/esteele/Code/local/sshkeys/github_wordspeak_deploy
        dest=/home/esteele/.ssh/github_wordspeak_deploy
        owner=esteele group=esteele mode=0600

# XXX should be line in file for deploy key, probably
- name: Setup personal ssh config
  copy: src=esteele_ssh_config
        dest=/home/esteele/.ssh/config owner=esteele group=esteele mode=0600

- name: Create Nikola Cache and Output directories
  file: path={{ item }} state=directory mode=0755 owner=esteele group=esteele
  with_items:
    - /home/esteele/tmp/nikola_wordspeak_cache
    - /home/esteele/tmp/nikola_wordspeak_output

# Enchant is used for spell checking
# libxslt is required to build the python lxml module
- name: Install packages required for Nikola use
  openbsd_pkg: name={{ item }} state=present
  with_items:
    - enchant
    - libxslt

- name: Add Github's ssh key
  lineinfile: mode="0644" owner="esteele" group="esteele"
              state="present" dest="/home/esteele/.ssh/known_hosts"
              create="yes"
              line='github.com,192.30.252.129 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='

# doas preserves USER and HOME, which is different to sudo, however by
#  specifying them as environment variables we can proceed.
# USER is required for git, and HOME is required for pip
- block:
  - name: Checkout wordspeak repo
    git: repo=ssh://git@github.com/edwinsteele/wordspeak.org.git
         dest=/home/esteele/Code/wordspeak.org
  
  - name: Setup nikola virtualenv
    pip: requirements=/home/esteele/Code/wordspeak.org/requirements.txt
         virtualenv_command=/usr/local/bin/virtualenv
         virtualenv=/home/esteele/.virtualenvs/wordspeak_n7

  become: True
  become_method: doas
  become_user: esteele
  environment:
    USER: esteele
    HOME: /home/esteele

