---
# cmake and boost are required for YCM
- name: Install standard packages
  openbsd_pkg:
    name: [ "{{ vim_package }}", "cmake", "boost" ]
    state: present
  become: True
  become_method: doas
  become_user: root

- name: Symlink dotfiles
  file:
    state: link
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: "/home/esteele/Code/dotfiles/vim/vimrc",
       dest: "/home/esteele/.vimrc" }
    - {src: "/home/esteele/Code/dotfiles/vim",
       dest: "/home/esteele/.vim" }

# Always use HEAD (hence skip_ansible_lint)
- name: Checkout vundle repo
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: /home/esteele/.vim/bundle/Vundle.vim
    depth: 1
  tags:
    - skip_ansible_lint

  #- name: Install vim plugins
  #  command: vim +PluginInstall +qall
  #  args:
  #    creates: /home/esteele/.vim/bundle/Vundle.vim/.git/FETCH_HEAD

  # Need followup step to perform YCM build

