---
- name: Only allow root login with keys
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin.*"
    line: "PermitRootLogin without-password"
    validate: "sshd -t -f %s"
  notify:
    - Restart sshd

- name: Don't allow auth with password
  lineinfile:
    dest: /etc/ssh/sshd_config
    insertafter: "^#PasswordAuthentication"
    line: "PasswordAuthentication no"
    validate: "sshd -t -f %s"
  notify:
  - Restart sshd

# Also takes care of .ssh directory setup
# This is the same key in the autoinstall
- name: setup authorised key for root
  authorized_key:
    user: root
    key: "{{ lookup('file', '/Users/esteele/.ssh/id_external_facing_root_ed25519.downloaded-from-1password.pub') }}"

- name: setup root password
  lineinfile:
    dest: /etc/master.passwd
    regexp: "^root:"
    line: 'root:{{ lookup("file", "/Users/esteele/Code/local_setup-scripts/ansible/root.hash" ) }}:0:0:daemon:0:0:Charlie &:/root:/bin/ksh'
  notify: Rebuild passwd database

- name: Set timezone as Sydney
  copy:
    src: /usr/share/zoneinfo/Australia/Sydney
    dest: /etc/localtime

- name: Enable and start ntpd
  service:
    name: ntpd
    state: started
    enabled: yes

- name: Setup /etc/hosts with FQDN
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.0.1'
    line: '127.0.0.1 localhost {{ ansible_fqdn }} {{ ansible_hostname }}'

- name: Create swap space as /home/swapfile
  command: dd if=/dev/zero of=/home/swapfile bs=1024 count=1000000
  when: ansible_swaptotal_mb < 950

- name: Set permissions on swapfile
  file:
    path: /home/swapfile
    mode: 0600
  when: ansible_swaptotal_mb < 950

- name: Enable swap on /home/swapfile
  command: swapctl -a /home/swapfile
  when: ansible_swaptotal_mb < 950

- name: Add swapfile to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "swapfile"
    line: "/home/swapfile /home/swapfile swap sw 0 0"
    state: present
  when: ansible_swaptotal_mb < 950

- name: Install standard packages
  openbsd_pkg:
    name: ['p5-ack', 'curl']

# Setup a bare-bones system python
- name: Install pip (system python)
  openbsd_pkg:
    name: "{{ python_pip_package }}"
    state: present

- name: Install virtualenv
  openbsd_pkg:
    name: "{{ python_virtualenv_package }}"
    state: present

- name: Schedule syspatch run via cron
  cron:
    name: Check for new syspatch patches
    special_time: daily
    job: syspatch -c
