---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Reload pf
  ansible.builtin.command: pfctl -f /etc/pf.conf

- name: Rebuild passwd database
  ansible.builtin.command: pwd_mkdb /etc/master.passwd
