# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "packer-openbsd62"
    config.vm.box_url = "../../packer/build/openbsd62-amd64-vmware.box"
    config.ssh.username = "root"
    config.ssh.private_key_path = "/Users/esteele/.ssh/id_rsa-packer-initial"
    config.ssh.shell = "/bin/ksh -l"
    config.ssh.sudo_command = "doas %c"
    config.vm.hostname = "devvm.grus.space"
    config.vm.define "devvm"

    # OpenBSD doesn't support the VirtualBox filesystem
    config.vm.synced_folder ".", "/vagrant", disabled: true

    # Wired ethernet on my hosts, then fall back to Wi-Fi (laptop only)
    #  which will be the correct device if travelling.
    config.vm.network "public_network", bridge: [
	"en7: Ethernet",
        "en0: Wi-Fi (AirPort)"
    ]

    config.vm.provision "ansible" do |ansible|
	ansible.playbook = "../../ansible/site.yml"
	ansible.groups = {
            "development" => ["devvm"]
	}
    end
end

