# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # Every Vagrant virtual environment requires a box to build off of.
    config.vm.box = "packer-openbsd59"
    config.vm.box_url = "../../packer/build/packer_openbsd59-amd64.box"
    config.ssh.username = "root"
    config.ssh.private_key_path = "/Users/esteele/.ssh/id_rsa-packer-initial"
    config.ssh.shell = "/bin/ksh -l"
    config.ssh.sudo_command = "doas %c"

    # OpenBSD doesn't support the VirtualBox filesystem
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.network "public_network", bridge: [
        "en4: AX88179 USB 3.0 to Gigabit Ethernet 3",
        "en0: Wi-Fi (AirPort)"
    ]
    # Assign this VM to a host-only network IP, allowing you to access it
    # via the IP. Host-only networks can talk to the host machine as well as
    # any other machines on the same network, but cannot be accessed (through this
    # network interface) by any external networks.
    #config.vm.network :private_network, ip: "192.168.56.151"

end

