---
- name: Allow CI to push staging web assets
  authorized_key:
    user: esteele
    state: present
    key_options: command="/usr/bin/openrsync --server -vlogDtpr --delete . /var/www/htdocs/{{ item.site }}/"
    key: "ssh-ed25519 {{ item.key }}"
  loop:
    - { site: staging.wordspeak.org, key: AAAAC3NzaC1lZDI1NTE5AAAAIK1Ss4dk6T9htQ7luQnVf+7TcJonZ+HV/9s12g6qBlRA }
    - { site: www.wordspeak.org, key: AAAAC3NzaC1lZDI1NTE5AAAAIH31nURuFbMiuV/Y0OT9fZEk87IOaP4jYLdvTx5VTNIt }

# We deliberately do not attempt to mount this because we do not want to fail
#  the playbook run if we haven't attached the disk to the VM (perhaps because
#  we're in testing). We do set it up in fstab though to make it easy to mount
#  when we get to it
- name: Setup /var/www/htdocs mount in fstab (if in AWS)
  mount:
    path: /var/www/htdocs
    src: "{{ var_www_htdocs_duid }}.a"
    fstype: ffs
    opts: rw,nodev,nosuid
    dump: "1"
    passno: "2"
    state: present
  when: "'amazon' in ansible_product_version"
