---
# Check dotfiles out now, but only link them up in the role where
#  they're actually used. Always use HEAD (hence skip_ansible_lint)
#
# Ignore errors so that we can have local uncommitted mods and still run
#  the playbook
- name: Checkout dotfiles repo
  git:
    repo: https://github.com/edwinsteele/dotfiles.git
    dest: /home/esteele/Code/dotfiles
  ignore_errors: yes
  tags:
    - skip_ansible_lint

