---
- name: Create dhcpd.conf
  template: src=dhcpd_conf.j2 dest=/etc/dhcpd.conf
            owner=root group=wheel mode=0644
            validate="dhcpd -n -c %s"
  notify: Restart dhcpd

- name: Enable and start dhcpd
  service: name=dhcpd state=started enabled=yes
          arguments="{{ internal_physical_interface }}"

# unbound-anchor has rc 1 when it has updated the root anchor
- name: Get root.key for dnssec
  command: unbound-anchor
  args:
    creates: /var/unbound/db/root.key
  ignore_errors: yes
  register: command_call
  changed_when: command_call.rc == 1

- name: Copy unbound local data config snippet
  template:
    src: unbound-local-data_conf.j2
    dest: /var/unbound/etc/unbound-local-data.conf
    owner: root
    group: wheel
    mode: 0644
  notify: Restart unbound

- name: Copy script to populate ad blocking config
  copy:
    src: generate_unbound_ads_conf.sh
    dest: /usr/local/bin/generate_unbound_ads_conf.sh
    mode: 0755

- name: Do first-run of ad-blocking script
  command: /usr/local/bin/generate_unbound_ads_conf.sh
  args:
    creates: /var/unbound/etc/unbound-adhosts.conf
  notify: Restart unbound

# Can't validate with unbound-checkconf unfortunately because the
# temporary file isn't under chroot
- name: Create unbound.conf
  template: src=unbound_conf.j2 dest=/var/unbound/etc/unbound.conf
            owner=root group=wheel mode=0644
  notify: Restart unbound

- name: Enable and start unbound
  service: name=unbound state=started enabled=yes
  notify: Update resolv.conf to use unbound

- name: Enable ipv4 ip forwarding
  lineinfile: dest=/etc/sysctl.conf state=present create=yes
              line="net.inet.ip.forwarding=1"
  notify: Enable ipv4 forwarding now via sysctl

- name: Schedule daily run of unbound ad-blocking script
  cron:
    name: Regenerate unbound ad-blocking list
    special_time: daily
    job: "/usr/local/bin/generate_unbound_ads_conf.sh"

- name: Manage limited internet access
  cron: name="{{ item.desc }} internet access for particular devices"
        minute="{{ item.min }}" hour="{{ item.hour }}"
        job="pfctl -q -t limited-internet-access -T {{ item.verb }} {{ limited_internet_access_addresses }}"
  with_items:
  - { desc: "Disable", verb: "add", hour: "5", min: "30" }
  - { desc: "Enable", verb: "delete", hour: "19", min: "30" }
