---
- name: setup pf.conf for this role
  template: src=pf_conf.j2 dest=/etc/pf.conf
            owner=root group=wheel mode=0600
            validate="pfctl -n -f %s"
  register: pf_conf_changed

- name: apply any new pf rules immediately
  command: pfctl -f /etc/pf.conf
  when: pf_conf_changed["changed"]

- name: Create dhcpd.conf
  template: src=dhcpd_conf.j2 dest=/etc/dhcpd.conf
            owner=root group=wheel mode=0644
            validate="dhcpd -n -c %s"
  notify: Restart dhcpd

- name: Enable and start dhcpd
  service: name=dhcpd state=started enabled=yes
          arguments="{{ internal_interface }} bwi0"

# Can't validate with unbound-checkconf unfortunately because the
# temporary file isn't under chroot
- name: Create unbound.conf
  template: src=unbound_conf.j2 dest=/var/unbound/etc/unbound.conf
            owner=root group=wheel mode=0644
  notify: Restart unbound

- name: Enable and start unbound
  service: name=unbound state=started enabled=yes
  notify: Update resolv.conf to use unbound

- name: Enable ipv4 ip forwarding
  lineinfile: dest=/etc/sysctl.conf state=present create=yes
              line="net.inet.ip.forwarding=1"
  notify: Enable ipv4 forwarding now via sysctl
