---
- name: setup pf.conf for this role
  template:
    src: "{{ pf_conf_template }}"
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: 0600
    validate: "pfctl -n -f %s"
  register: pf_conf_changed

- name: apply any new pf rules immediately
  command: pfctl -f /etc/pf.conf
  when: pf_conf_changed["changed"]
