---
- name: setup pf.conf for this role
  template:
    src: "{{ pf_conf_template }}"
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: 0600
    validate: "pfctl -n -f %s"
  register: pf_conf_changed

# This needs to run immediately so that any newly provisioned
#  network-accessible services are firewalled correctly from the outset
- name: apply any new pf rules immediately  # noqa 503
  command: pfctl -f /etc/pf.conf
  when: pf_conf_changed["changed"]
