---
- name: Restart dhcpd
  service:
    name: dhcpd
    state: restarted

- name: Restart unbound
  service:
    name: unbound
    state: restarted

# We start using unbound after it has been restarted as we don't
#  want to break DNS on the host
- name: Update resolv.conf to use unbound
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: wheel
    mode: 0644

- name: Enable ipv4 forwarding now via sysctl
  command: sysctl net.inet.ip.forwarding=1
