# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.box = "Puppetlabs Fedora 18 x86_64, VBox 4.2.10, No Puppet or Chef"
  #config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/fedora-18-x64-vbox4210-nocm.box"
  config.vm.box = "Puppet Labs CentOS 6.4 x64 vbox4210 nocm"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box"
  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "/Users/esteele/Documents/VagrantShared", "/vagrant_shared"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../../ansible/wordspeak/initial.yml"
    ansible.inventory_file = "ansible_hosts"
  end
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../../ansible/wordspeak/wordspeak-deploy.yml"
    ansible.inventory_file = "ansible_hosts"
  end
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../../ansible/wordspeak/esteele.yml"
    ansible.inventory_file = "ansible_hosts"
  end

  config.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "512"]
  end
end
