# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "Puppet Labs CentOS 6.5 x64 vbox436 nocm"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box"
  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "/Users/esteele/Documents/VagrantShared", "/vagrant_shared"

  config.vm.provision :ansible do |ansible|
    ansible.inventory_path = "../../ansible/hosts"
    ansible.limit = "local-linux"
    ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
    ansible.playbook = "../../ansible/wordspeak/initial.yml"
  end
  config.vm.provision :ansible do |ansible|
    ansible.inventory_path = "../../ansible/hosts"
    ansible.limit = "local-linux"
    ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
    ansible.playbook = "../../ansible/wordspeak/base_nginx.yml"
  end
  config.vm.provision :ansible do |ansible|
    ansible.inventory_path = "../../ansible/hosts"
    ansible.limit = "local-linux"
    ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
    ansible.playbook = "../../ansible/wordspeak/python27-setup.yml"
  end
  config.vm.provision :ansible do |ansible|
    ansible.inventory_path = "../../ansible/hosts"
    ansible.limit = "local-linux"
    ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
    ansible.playbook = "../../ansible/wordspeak/esteele.yml"
  end
  config.vm.provision :ansible do |ansible|
    ansible.inventory_path = "../../ansible/hosts"
    ansible.limit = "local-linux"
    ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
    ansible.playbook = "../../ansible/wordspeak/wordspeak-deploy.yml"
  end
  config.vm.provision :ansible do |ansible|
    ansible.inventory_path = "../../ansible/hosts"
    ansible.limit = "local-linux"
    ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
    ansible.playbook = "../../ansible/wordspeak/language_explorer.yml"
  end

  config.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "512"]
  end
end
