---
- name: Restart smb
  ansible.builtin.service:
    name: smb
    state: restarted

- name: Restart avahi-daemon
  ansible.builtin.service:
    name: avahi-daemon
    state: restarted

- name: Apply SELinux context on share
  ansible.builtin.command: "restorecon -RF {{ samba_timemachine_share_path }}"
