# -*- mode: ruby -*-
# vi: set ft=ruby :
# 
- hosts: vagrant
  user: root
  sudo: yes
  gather_facts: yes

  tasks:
    # NGINX repo
    #TODO - install key with rpm_key
    - name: Install NGINX repo for CentOS6
      command: yum -y install http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
                creates=/etc/yum.repos.d/nginx.repo
      when: ansible_os_family == "RedHat"

    # nginx is already on OpenBSD
    - name: Install nginx (CentOS only)
      yum: name=nginx state=present
      when: ansible_os_family == "RedHat"

    - name: Create base nginx directories
      file: path=/etc/nginx/conf.d owner=root group=wheel state=directory

    - name: Setup base nginx config
      template: src=templates/nginx.j2 dest=/etc/nginx/nginx.conf
                 owner=root group=wheel mode=0644
    - name: Setup base nginx mime types
      template: src=templates/nginx_mime_types.j2 dest=/etc/nginx/mime.types
                 owner=root group=wheel mode=0644
    - name: Setup nginx default site config
      template: src=templates/nginx_confd_default.j2
                 dest=/etc/nginx/conf.d/default.conf
                 owner=root group=wheel mode=0644

    - name: Create base directory for random parameter
      file: path=/etc/ssl/certs/misc owner=root group=wheel state=directory

    - name: Generate 2048bit random parameter for nginx DH Elliptic Curves
      command: openssl dhparam -outform pem -out /etc/ssl/certs/misc/nginx-dhparam2048.pem 2048
                creates=/etc/ssl/certs/misc/nginx-dhparam2048.pem

    - name: Enable and start nginx
      action: service name=nginx state=started enabled=yes
