# -*- mode: ruby -*-
# vi: set ft=ruby :
# 
- hosts: vagrant
  user: root
  sudo: yes
  gather_facts: yes
  vars_files:
    - vars/defaults.yml

  tasks:
    # NGINX repo
    #TODO - install key with rpm_key
    - name: Install NGINX repo for CentOS6
      command: yum -y install http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
                creates=/etc/yum.repos.d/nginx.repo

    # nginx
    - name: Install nginx
      yum: name=nginx state=present
    - name: Setup base nginx config
      template: src=templates/nginx.j2 dest=/etc/nginx/nginx.conf
                 owner=root group=root mode=0644
    - name: Setup base nginx mime types
      template: src=templates/nginx_mime_types.j2 dest=/etc/nginx/mime.types
                 owner=root group=root mode=0644
    - name: Setup nginx default site config
      template: src=templates/nginx_confd_default.j2
                 dest=/etc/nginx/conf.d/default.conf
                 owner=root group=root mode=0644
    - name: Generate 2048bit random parameter for nginx DH Elliptic Curves
      command: openssl dhparam -outform pem -out /etc/pki/tls/misc/nginx-dhparam2048.pem 2048
                creates=/etc/pki/tls/misc/nginx-dhparam2048.pem

    - name: Enable and start nginx
      action: service name=nginx state=started enabled=yes
