---
# Non-system packages to allow the build and deployment of the wordspeak site

- hosts: vagrant
  sudo: yes
  sudo_user: root
  gather_facts: yes

  tasks:
    - name: create esteele group
      action: group name=esteele gid=1003 system=no

    - name: create user(s)
      action: user name=esteele group=esteele groups=admin shell=/bin/bash uid=1003

    - name: setup authorised key(s)
      sudo: True
      sudo_user: esteele
      action: authorized_key user=esteele key="{{ lookup('file', '/Users/esteele/.ssh/id_rsa.pub') }}"

    - name: Setup git user.email variable for esteele
      sudo: True
      sudo_user: esteele
      ini_file: dest=/home/esteele/.gitconfig section=user
                 option=email value=edwin@wordspeak.org      

    - name: Setup git user.name variable for esteele
      sudo: True
      sudo_user: esteele
      ini_file: dest=/home/esteele/.gitconfig section=user
                 option=name value="Edwin Steele"

    - name: Setup private_profile placeholder
      sudo: True
      sudo_user: esteele
      file: path=/home/esteele/.profile_private mode=0600 state=touch

    - name: Setup git push style for esteele
      sudo: True
      sudo_user: esteele
      ini_file: dest=/home/esteele/.gitconfig section=push
                 option=default value=current

    - name: Setup ~esteele/Code
      sudo: True
      sudo_user: esteele
      file: path=/home/esteele/Code state=directory

    - name: Setup ~esteele/Sites
      sudo: True
      sudo_user: esteele
      file: path=/home/esteele/Code state=directory

    - name: Fix perms on ~esteele to allow ~/Sites to be served up
      sudo: True
      sudo_user: esteele
      file: path=/home/esteele state=directory mode=0711

    - name: Download dropbox daemon
      sudo: True
      sudo_user: esteele
      shell: cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf - creates=/home/esteele/.dropbox-dist

    - name: Download dropbox daemon
      sudo: True
      sudo_user: esteele
      get_url: url=https://www.dropbox.com/download?dl=packages/dropbox.py dest=/home/esteele/.dropbox-dist/dropbox.py mode=0750
