---
# Non-system packages to allow the build and deployment of the wordspeak site

- hosts: vagrant
  sudo: yes
  sudo_user: esteele
  gather_facts: yes

  tasks:
    - name: Setup git user.email variable for esteele
      ini_file: dest=/home/esteele/.gitconfig section=user
                 option=email value=edwin@wordspeak.org      

    - name: Setup git user.name variable for esteele
      ini_file: dest=/home/esteele/.gitconfig section=user
                 option=user value="Edwin Steele"

    - name: Setup staging.wordspeak.org parent directory
      file: path=/home/esteele/Sites/staging.wordspeak.org state=directory
             mode=0711 owner=esteele group=esteele

    - name: Install Nikola with deps into wordspeak venv
      pip: name=nikola
            virtualenv=/home/esteele/.virtualenvs/wordspeak

    - name: Create Nikola Cache directory
      file: path=/home/esteele/tmp/nikola_wordspeak_cache state=directory
             mode=0755 owner=esteele group=esteele

    - name: Create Nikola Output directory
      file: path=/home/esteele/tmp/nikola_wordspeak_output state=directory
             mode=0755 owner=esteele group=esteele

    # Setup linkchecker. Pip doesn't support xz and the developer
    #  only provides xz archives.
    - name: Fetch linkchecker source
      get_url: url=http://github.com/downloads/wummel/linkchecker/LinkChecker-8.4.tar.xz
                dest=/tmp/LinkChecker-8.4.tar.xz
    - name: Uncompress linkchecker source
      command: xz -d /tmp/LinkChecker-8.4.tar.xz chdir=/tmp 
                creates=/tmp/LinkChecker-8.4.tar
    # Pip module can't install from a tar file
    # FIXME - centos 6.4 has python 2.6, not 2.7 (like fedora)
    - name: Pip install linkchecker from local files into wordspeak venv
      command: /home/esteele/.virtualenvs/wordspeak/bin/pip install /tmp/LinkChecker-8.4.tar
            creates=/home/esteele/.virtualenvs/wordspeak/lib/python2.6/site-packages/LinkChecker-8.4-py2.6.egg-info/PKG-INFO
  
    # git checkout of wordspeak repo to ~/Code/wordspeak
