---
# Non-system packages to allow the build and deployment of the wordspeak site

- hosts: all
  sudo: yes
  sudo_user: root
  gather_facts: yes

  tasks:
    - name: create esteele group
      action: group name=esteele gid=1003 system=no

    - name: create user(s)
      action: user name=esteele group=esteele groups=admin uid=1003

    - name: Set login class (OpenBSD)
      user: login_class=staff name=esteele
      when: ansible_os_family == "OpenBSD"

    - name: setup authorised key(s)
      sudo: True
      sudo_user: esteele
      action: authorized_key user=esteele key="{{ lookup('file', '/Users/esteele/.ssh/id_rsa.pub') }}"

    # Have this run after there's a task that runs as esteele so the
    #  skeleton .profile is in place
    # OpenBSD data segment limits are too small to allow building of python lxml
    - name: Increase data segment ulimit (OpenBSD)
      lineinfile: dest=/home/esteele/.profile line="ulimit -Sd 1000000" state=present
      when: ansible_os_family == "OpenBSD"

    - name: Setup git user.email variable for esteele
      sudo: True
      sudo_user: esteele
      ini_file: dest=/home/esteele/.gitconfig section=user
                 option=email value=edwin@wordspeak.org      

    - name: Setup git user.name variable for esteele
      sudo: True
      sudo_user: esteele
      ini_file: dest=/home/esteele/.gitconfig section=user
                 option=name value="Edwin Steele"

    - name: Setup private_profile placeholder
      sudo: True
      sudo_user: esteele
      file: path=/home/esteele/.profile_private mode=0600 state=touch

    - name: Setup git push style for esteele
      sudo: True
      sudo_user: esteele
      ini_file: dest=/home/esteele/.gitconfig section=push
                 option=default value=current

    - name: Setup ~esteele/Code
      sudo: True
      sudo_user: esteele
      file: path=/home/esteele/Code state=directory
