---
- hosts: vagrant
  user: root
  sudo: yes
  gather_facts: yes
  vars_files:
    - vars/defaults.yml

  tasks:

    - name: Install python-selinux compatibility packages
      yum: name=policycoreutils-python state=present

    - name: Install other python-selinux compatibility packages
      yum: name=libselinux-python state=present

    # Configure users and groups
    - name: create admin group
      action: group name=admin gid=1002 system=no

    - name: create esteele group
      action: group name=esteele gid=1003 system=no

    - name: create user(s)
      action: user name=esteele group=esteele groups=admin shell=/bin/bash uid=1003

    - name: setup authorised key(s)
      action: authorized_key user=esteele key='$FILE(/Users/esteele/.ssh/id_rsa.pub)'

    # Access, security and perms
    - name: write the sudoers file
      template: src=templates/custom_sudo.j2 dest=/etc/sudoers.d/wordspeak
                 owner=root group=root mode=0400
    - name: write the sshd_config file
      template: src=templates/sshd_config.j2 dest=/etc/ssh/sshd_config
              owner=root group=root mode=0600
      notify:
        - Reload sshd

    # Firewall
    - name: Enable inbound TCP port 80 in firewall
      action: lineinfile dest=/etc/sysconfig/iptables state=present
               line='-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT'
               regexp='^-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT$'
               insertafter='^-A INPUT -i lo -j ACCEPT$'
      notify: Restart iptables

    - name: Enable inbound UDP port 60000-60001 in firewall for mosh
      action: lineinfile dest=/etc/sysconfig/iptables state=present
               line='-A INPUT -m state --state NEW -m multiport -p udp --dports 60000:60001 -j ACCEPT'
               regexp='^-A INPUT -m state --state NEW -m multiport -p udp --dports 60000:60001 -j ACCEPT$'
               insertafter='^-A INPUT -i lo -j ACCEPT$'
      notify: Restart iptables

    # FIXME - this copies from the host, not within the VM!!!
    - name: Set timezone as Sydney
      copy: src=/usr/share/zoneinfo/Australia/Sydney dest=/etc/localtime

    # ntp
    - yum: name=ntp state=present
    - name: Ensure NTP is up and running
      action: service name=ntpd state=started

    # EPEL for RHEL6 (needed for nginx, mosh and tmux)
    - name: Install EPEL for RHEL6 (only if RHEL6)
      command: yum -y install http://mirror.iprimus.com.au/epel/6/i386/epel-release-6-8.noarch.rpm
                creates=/etc/yum.repos.d/epel.repo
      #when: "ansible_os_family == 'RedHat' and ansible_distribution_version == '6.4'"  # FIXME - just want 6 from 6.4
      when: ansible_os_family == "RedHat"

    # nginx
    - yum: name=nginx state=present
    - name: Setup base nginx config
      template: src=templates/nginx.j2 dest=/etc/nginx/nginx.conf
                 owner=root group=root mode=0644
    - name: Setup nginx default site config
      template: src=templates/nginx_confd_default.j2
                 dest=/etc/nginx/conf.d/default.conf
                 owner=root group=root mode=0644
    - name: Setup nginx wordspeak staging config
      template: src=templates/nginx_confd_staging_wordspeak_org.j2
                 dest=/etc/nginx/conf.d/staging_wordspeak_org.conf
                 owner=root group=root mode=0644

    - yum: name=mosh state=present
    - yum: name=tmux state=present
    - yum: name=git state=present
    - yum: name=wget state=present



  handlers:
    - name: Reload sshd
      action: service name=sshd state=reloaded

    - name: Restart iptables
      action: service name=iptables state=restarted
