---
- hosts: vagrant
  user: vagrant
  sudo: yes
  gather_facts: no
  vars_files:
    - vars/defaults.yml

  tasks:

    # Configure users and groups
    - name: create admin group
      action: group name=admin gid=1002 system=no

    - name: create esteele group
      action: group name=esteele gid=1003 system=no

    - name: create user(s)
      action: user name=esteele group=esteele groups=admin shell=/bin/bash uid=1003

    - name: setup authorised key(s)
      action: authorized_key user=esteele key='$FILE(/Users/esteele/.ssh/id_rsa.pub)'

    # Access, security and perms
    - name: write the sudoers file
      template: src=templates/custom_sudo.j2 dest=/etc/sudoers.d/wordspeak
                 owner=root group=root mode=0400
    - name: write the sshd_config file
      template: src=templates/sshd_config.j2 dest=/etc/ssh/sshd_config
              owner=root group=root mode=0600
      notify:
        - Reload sshd

    - name: Set timezone as Sydney
      copy: src=/usr/share/zoneinfo/Australia/Sydney dest=/etc/localtime

    # ntp
    - yum: name=ntp state=present
    - name: Ensure NTP is up and running
      action: service name=ntpd state=started

    # EPEL for RHEL6 (needed for nginx, mosh and tmux)
    - name: Install EPEL for RHEL6 (only if RHEL6)
      command: yum -y install http://mirror.iprimus.com.au/epel/6/i386/epel-release-6-8.noarch.rpm
                creates=/etc/yum.repos.d/epel.repo
      when: ansible_os_family == “RedHat” and ansible_lsb.major_release|int >= 6

    # nginx
    - yum: name=nginx state=present
    - name: Setup base nginx config
      template: src=templates/nginx.j2 dest=/etc/nginx/nginx.conf
                 owner=root group=root mode=0644
    - name: Setup nginx default site config
      template: src=templates/nginx_confd_default.j2
                 dest=/etc/nginx/conf.d/default.conf
                 owner=root group=root mode=0644
    - name: Setup nginx wordspeak staging config
      template: src=templates/nginx_confd_staging_wordspeak_org.j2
                 dest=/etc/nginx/conf.d/staging_wordspeak_org.conf
                 owner=root group=root mode=0644

    - yum: name=mosh state=present
    - yum: name=tmux state=present
    - yum: name=git state=present



  handlers:
    - name: Reload sshd
      action: service name=sshd state=reloaded
