# -*- mode: ruby -*-
# vi: set ft=ruby :
# 
- hosts: all
  user: root
  sudo: yes
  gather_facts: yes

  tasks:

    # Access, security and perms
    # Fully quoted because of the ': ' on the line. See the Gotchas in the YAML docs.
    - name: Give the admin group sudo privileges
      lineinfile: 'dest=/etc/sudoers line="%wheel        ALL=(ALL) NOPASSWD: SETENV: ALL" validate="visudo -c -f %s"'

    - name: Only allow root login with keys
      lineinfile: dest=/etc/ssh/sshd_config
                insertafter="^#PermitRootLogin"
                line="PermitRootLogin without-password" validate="sshd -t -f %s"
      notify:
        - Restart sshd

    - name: Don't allow auth with password
      lineinfile: dest=/etc/ssh/sshd_config
                insertafter="^#PasswordAuthentication"
                line="PasswordAuthentication no" validate="sshd -t -f %s"
      notify:
        - Restart sshd

    # Firewall
    # XXX - todo on OpenBSD (port 80, 22 and 443 only)

    - name: Set timezone as Sydney
      copy: src=/usr/share/zoneinfo/Australia/Sydney dest=/etc/localtime

    - name: Enable and start ntpd
      action: service name=ntpd state=started enabled=yes

    - name: Create swap space as /home/swapfile
      command: dd if=/dev/zero of=/home/swapfile bs=1024 count=500000
      when: ansible_swaptotal_mb < 950

    - name: Set permissions on swapfile
      file: path=/home/swapfile mode=0600

    - name: Enable swap on /home/swapfile (OpenBSD)
      command: swapctl -a /home/swapfile
      when: ansible_swaptotal_mb < 950

    - name: Add swapfile to fstab (OpenBSD)
      action: lineinfile dest=/etc/fstab regexp="swapfile" line="/home/swapfile /home/swapfile swap sw 0 0" state=present

    - openbsd_pkg: name=git state=present
      environment:
          PKG_PATH: "{{PKG_PATH}}"
    - openbsd_pkg: name=p5-ack state=present
      environment:
          PKG_PATH: "{{PKG_PATH}}"
    - openbsd_pkg: name=wget state=present
      environment:
          PKG_PATH: "{{PKG_PATH}}"
    - openbsd_pkg: name=vim--no_x11 state=present
      environment:
          PKG_PATH: "{{PKG_PATH}}"
    - openbsd_pkg: name=curl state=present
      environment:
          PKG_PATH: "{{PKG_PATH}}"
    - openbsd_pkg: name=lsof state=present
      environment:
          PKG_PATH: "{{PKG_PATH}}"


  handlers:
    - name: Restart sshd
      action: service name=sshd state=restarted
