# -*- mode: ruby -*-
# vi: set ft=ruby :
# 
- hosts: vagrant
  user: root
  sudo: yes
  gather_facts: yes

  tasks:

    - name: Install python-selinux compatibility packages
      yum: name=policycoreutils-python state=present

    - name: Install other python-selinux compatibility packages
      yum: name=libselinux-python state=present

    - name: create admin group
      action: group name=admin gid=1002 system=no

    # Access, security and perms
    - name: write the sudoers file
      template: src=templates/custom_sudo.j2 dest=/etc/sudoers.d/wordspeak
                 owner=root group=root mode=0400
    - name: write the sshd_config file
      template: src=templates/sshd_config.j2 dest=/etc/ssh/sshd_config
              owner=root group=root mode=0600
      notify:
        - Reload sshd

    # Firewall
    - name: create a base firewall config
      template: src=templates/iptables.j2 dest=/etc/sysconfig/iptables
                 owner=root group=root mode=0600
    - name: Enable inbound TCP port 80 in firewall
      action: lineinfile dest=/etc/sysconfig/iptables create=yes state=present
               line='-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT'
               regexp='^-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT$'
               insertafter='^-A INPUT -i lo -j ACCEPT$'
      notify: Restart iptables
    - name: Enable inbound TCP port 443 in firewall
      action: lineinfile dest=/etc/sysconfig/iptables create=yes state=present
               line='-A INPUT -m state --state NEW -m tcp -p tcp --dport 443 -j ACCEPT'
               regexp='^-A INPUT -m state --state NEW -m tcp -p tcp --dport 443 -j ACCEPT$'
               insertafter='^-A INPUT -i lo -j ACCEPT$'
      notify: Restart iptables

    # XXX Fix this to use /etc/sysconfig/clock instead
    - name: Set timezone as Sydney
      command: cp /usr/share/zoneinfo/Australia/Sydney /etc/localtime

    - name: Ensure NTP is up and running
      yum: name=ntp state=present
    - name: Enable and start ntpd
      action: service name=ntpd state=started enabled=yes

    - name: Create swap space as /swapfile
      command: dd if=/dev/zero of=/swapfile bs=1024 count=1000000
      when: ansible_swaptotal_mb < 1

    - name: Make /swapfile into a swapfile
      command: mkswap /swapfile
      when: ansible_swaptotal_mb < 1

    - name: Enable swap on /swapfile
      command: swapon /swapfile
      when: ansible_swaptotal_mb < 1

    - name: Add /swapfile to fstab
      action: lineinfile dest=/etc/fstab regexp="swapfile" line="/swapfile none swap sw 0 0" state=present

    # EPEL for RHEL6 (needed for tmux)
    #TODO - install key with rpm_key
    - name: Install EPEL for RHEL6
      yum: name=epel-release state=present

    - yum: name=bash-completion state=present
    - yum: name=tmux state=present
    - yum: name=git state=present
    - yum: name=ack state=present
    - yum: name=wget state=present
    - yum: name=bind-utils state=present
    - yum: name=vim-enhanced state=present



  handlers:
    - name: Reload sshd
      action: service name=sshd state=reloaded

    - name: Restart iptables
      action: service name=iptables state=restarted
