# -*- mode: ruby -*-
# vi: set ft=ruby :
# 
- hosts: vagrant
  user: root
  sudo: yes
  gather_facts: yes
  vars_files:
    - vars/defaults.yml

  tasks:

    - name: Install python-selinux compatibility packages
      yum: name=policycoreutils-python state=present

    - name: Install other python-selinux compatibility packages
      yum: name=libselinux-python state=present

    - name: create admin group
      action: group name=admin gid=1002 system=no

    # Access, security and perms
    - name: write the sudoers file
      template: src=templates/custom_sudo.j2 dest=/etc/sudoers.d/wordspeak
                 owner=root group=root mode=0400
    - name: write the sshd_config file
      template: src=templates/sshd_config.j2 dest=/etc/ssh/sshd_config
              owner=root group=root mode=0600
      notify:
        - Reload sshd

    # Firewall
    - name: Enable inbound TCP port 80 in firewall
      action: lineinfile dest=/etc/sysconfig/iptables state=present
               line='-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT'
               regexp='^-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT$'
               insertafter='^-A INPUT -i lo -j ACCEPT$'
      notify: Restart iptables
    - name: Enable inbound TCP port 443 in firewall
      action: lineinfile dest=/etc/sysconfig/iptables state=present
               line='-A INPUT -m state --state NEW -m tcp -p tcp --dport 443 -j ACCEPT'
               regexp='^-A INPUT -m state --state NEW -m tcp -p tcp --dport 443 -j ACCEPT$'
               insertafter='^-A INPUT -i lo -j ACCEPT$'
      notify: Restart iptables

    # XXX Fix this to use /etc/sysconfig/clock instead
    - name: Set timezone as Sydney
      command: cp /usr/share/zoneinfo/Australia/Sydney /etc/localtime

    - name: Ensure NTP is up and running
      yum: name=ntp state=present
    - name: Enable and start ntpd
      action: service name=ntpd state=started enabled=yes

    # EPEL for RHEL6 (needed for nginx and tmux)
    #TODO - install key with rpm_key
    - name: Install EPEL for RHEL6
      command: yum -y install http://mirror.iprimus.com.au/epel/6/i386/epel-release-6-8.noarch.rpm
                creates=/etc/yum.repos.d/epel.repo

    # NGINX repo
    #TODO - install key with rpm_key
    - name: Install NGINX repo for CentOS6
      command: yum -y install http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
                creates=/etc/yum.repos.d/nginx.repo

    # nginx
    - name: Install nginx
      yum: name=nginx state=present
    - name: Setup base nginx config
      template: src=templates/nginx.j2 dest=/etc/nginx/nginx.conf
                 owner=root group=root mode=0644
    - name: Setup base nginx mime types
      template: src=templates/nginx_mime_types.j2 dest=/etc/nginx/mime.types
                 owner=root group=root mode=0644
    - name: Setup nginx default site config
      template: src=templates/nginx_confd_default.j2
                 dest=/etc/nginx/conf.d/default.conf
                 owner=root group=root mode=0644
    - name: Setup nginx staging.wordspeak.org config
      template: src=templates/nginx_confd_staging_wordspeak_org.j2
                 dest=/etc/nginx/conf.d/staging_wordspeak_org.conf
                 owner=root group=root mode=0644
    - name: Setup nginx www.wordspeak.org config
      template: src=templates/nginx_confd_www_wordspeak_org.j2
                 dest=/etc/nginx/conf.d/www_wordspeak_org.conf
                 owner=root group=root mode=0644

    - name: Generate 2048bit random parameter for nginx DH Elliptic Curves
      command: openssl dhparam -outform pem -out /etc/pki/tls/misc/nginx-dhparam2048.pem 2048
                creates=/etc/pki/tls/misc/nginx-dhparam2048.pem

    - name: Copy ssl chained cert
      copy: src=/Users/esteele/Code/local/startssl/wordspeak.org.chained.crt
             dest=/etc/ssl/certs/wordspeak.org.chained.crt owner=root group=root mode=0644
    - name: Copy ssl trusted chained cert
      copy: src=/Users/esteele/Code/local/startssl/wordspeak.org.chained.trusted.crt
             dest=/etc/ssl/certs/wordspeak.org.chained.trusted.crt owner=root group=root mode=0644
    - name: Copy certificate key
      copy: src=/Users/esteele/Code/local/startssl/my-private-decrypted.key
             dest=/etc/ssl/certs/wordspeak.org.ssl.key owner=root group=root mode=0600

    - name: Enable and start nginx
      action: service name=nginx state=started enabled=yes

    - yum: name=bash-completion state=present
    - yum: name=tmux state=present
    - yum: name=git state=present
    - yum: name=ack state=present
    - yum: name=wget state=present
    - yum: name=bind-utils state=present
    - yum: name=vim-enhanced state=present



  handlers:
    - name: Reload sshd
      action: service name=sshd state=reloaded

    - name: Restart iptables
      action: service name=iptables state=restarted
