# -*- mode: ruby -*-
# vi: set ft=ruby :
# 
# Non-system packages to allow the build and deployment of the language_explorer
# Assumes python27-setup.yml has been run before

- hosts: vagrant
  sudo: yes
  sudo_user: root
  gather_facts: yes

  tasks:
    - name: Install Postgres server
      yum: name=postgresql-server state=present

    - name: Initialise postgres
      command: service postgresql initdb
      args: 
              creates: /var/lib/pgsql/data/PG_VERSION

    - name: Enable and start Postgres/Postmaster
      action: service name=postgresql state=started enabled=yes

    - name: Install Postgres client
      yum: name=postgresql state=present

    - name: Install postgres-devel for subsequent admin tasks
      yum: name=postgresql-devel state=present

    - name: Install python-devel for subsequent admin tasks
      yum: name=python-devel state=present

    - name: Install psycopg2 for subsequent admin tasks
      pip: name=psycopg2 state=present

    - name: Setup esteele postgres user
      sudo: True
      sudo_user: postgres
      postgresql_user: name=esteele role_attr_flags=CREATEDB,NOSUPERUSER

    - name: Setup esteele postgres db
      sudo: True
      sudo_user: postgres
      postgresql_db: name=esteele

    - name: Setup language_explorer postgres db
      sudo: True
      sudo_user: postgres
      postgresql_db: name=language_explorer

    - name: Setup language_explorer venv with gunicorn
      sudo: True
      sudo_user: esteele
      pip: name=gunicorn virtualenv_command=virtualenv-2.7
            virtualenv=/home/esteele/.virtualenvs/language_explorer

# nginx setup
# gunicorn setup
