# -*- mode: ruby -*-
# vi: set ft=ruby :
# 
- hosts: all
  user: root
  sudo: yes
  gather_facts: yes

  tasks:
    - name: Setup base nginx config
      template: src=templates/httpd_conf.j2 dest=/etc/httpd.conf
                 owner=root group=wheel mode=0644
    - name: Create base directory for certificates
      file: path=/etc/ssl/certs owner=root group=wheel state=directory

    - name: Copy ssl chained cert
      copy: src=/Users/esteele/Code/local/startssl/wordspeak.org.chained.crt
             dest=/etc/ssl/certs/wordspeak.org.chained.crt owner=root group=wheel mode=0644
    - name: Copy ssl trusted chained cert
      copy: src=/Users/esteele/Code/local/startssl/wordspeak.org.chained.trusted.crt
             dest=/etc/ssl/certs/wordspeak.org.chained.trusted.crt owner=root group=wheel mode=0644
    - name: Copy certificate key
      copy: src=/Users/esteele/Code/local/startssl/www_wordspeak_org.key
             dest=/etc/ssl/certs/wordspeak.org.ssl.key owner=root group=wheel mode=0600

    - name: Enable and start httpd
      action: service name=httpd state=started enabled=yes
