---
# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# system packages to support use of python27 and virtualenvs
- hosts: all
  sudo: yes
  sudo_user: root
  gather_facts: yes

  tasks:
    - name: Install gcc for module compilation
      yum: name=gcc state=present
      when: ansible_os_family == "RedHat"
    - name: Install python-devel for module compilation (system python 2.6)
      yum: name=python-devel state=present
      when: ansible_os_family == "RedHat"

    # Hack to setup psycopg2 before we replace the default python interpreter
    - name: Install pip (system python 2.6)
      yum: name=python-pip state=present
      when: ansible_os_family == "RedHat"
    - name: Install pip (system python)
      openbsd_pkg: name=py-pip state=present
      when: ansible_os_family == "OpenBSD"
      environment:
          PKG_PATH: "{{PKG_PATH}}"
    - name: Install postgres-devel for subsequent admin tasks
      yum: name=postgresql-devel state=present
      when: ansible_os_family == "RedHat"
    - name: Install psycopg2 for subsequent admin tasks
      pip: name=psycopg2 state=present executable="{{system_pip_location}}"

      # Python 2.7.9 RPMs made with https://github.com/jyoo/python27-for-centos6
    - name: Copy Python 2.7.9 RPM to the new machine
      copy: src=/Users/esteele/Software/python27-for-centos6/rpms/python27-2.7.9-1.x86_64.rpm
             dest=/tmp/python27-2.7.9-1.x86_64.rpm
      when: ansible_os_family == "RedHat"
    - name: Copy Python 2.7.9 devel RPM to the new machine
      copy: src=/Users/esteele/Software/python27-for-centos6/rpms/python27-devel-2.7.9-1.x86_64.rpm
             dest=/tmp/python27-devel-2.7.9-1.x86_64.rpm
      when: ansible_os_family == "RedHat"

    - name: Install Python 2.7.9 from recently copied files
      yum: name=/tmp/python27-2.7.9-1.x86_64.rpm state=present
      when: ansible_os_family == "RedHat"
    - name: Install Python devel 2.7.9 from recently copied files
      yum: name=/tmp/python27-devel-2.7.9-1.x86_64.rpm state=present
      when: ansible_os_family == "RedHat"

    # Only need to run this on redhat as pip is installed with openbsd pkg
    - name: Install pip and easy_install using ensurepip (works with 2.7.9+)
      command: /usr/local/bin/python2.7 -m ensurepip --upgrade creates=/usr/local/bin/pip2.7
      when: ansible_os_family == "RedHat"

    - name: Install virtualenv using easy_install
      command: /usr/local/bin/easy_install-2.7 virtualenv creates=/usr/local/bin/virtualenv-2.7

