---
# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# system packages to support use of python27 and virtualenvs
- hosts: vagrant
  sudo: yes
  sudo_user: root
  gather_facts: yes

  tasks:
    - name: Install gcc for module compilation
      yum: name=gcc state=present
    - name: Install python-devel for module compilation (system python 2.6)
      yum: name=python-devel state=present

    - name: Retrieve PUIAS GPG key
      get_url: url=http://springdale.math.ias.edu/data/puias/6/x86_64/os/RPM-GPG-KEY-puias
                dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-puias
    - name: Import PUIAS GPG key
      rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-puias
    - name: Setup PUIAS computational repo
      template: src=templates/puais-computational.repo.j2 dest=/etc/yum.repos.d/puais-computational.repo

    - name: Install Python 2.7 from PUIAS computational repo
      yum: name=python27 state=present
    - name: Install Python 2.7 devel from PUIAS computational repo
      yum: name=python27-devel state=present
    - name: Install Python 2.7 setuptools from PUIAS computational repo
      yum: name=python27-setuptools state=present

    - name: Install pip-2.7 using easy_install
      command: /usr/bin/easy_install-2.7 pip creates=/usr/bin/pip2.7

    - name: Install virtualenv-2.7 using easy_install
      command: /usr/bin/easy_install-2.7 virtualenv creates=/usr/bin/virtualenv-2.7

    # Install this last, so that pip points to system python (which is required for postgres tasks)
    - name: Install pip (system python 2.6)
      yum: name=python-pip state=present
