---
# system packages to support the build and deployment of the wordspeak site
- hosts: vagrant
  user: vagrant
  sudo: yes
  gather_facts: yes
  vars_files:
    - vars/defaults.yml

  tasks:
    - name: Install xz for subsequent Linkchecker setup
      yum: name=xz state=present

    # Python stuff
    - name: Install pip for system python
      yum: name=python-pip state=present

    - name: Install virtualenv as system site-package
      pip: name=virtualenv

    - name: Install python-devel for module compilation
      yum: name=python-devel state=present
    - name: Install enchant for spell checking
      yum: name=enchant state=present
    - name: Install enchant-aspell for aspell compatibility
      yum: name=enchant-aspell state=present
    - name: Install GB English aspell dictionary
      yum: name=aspell-en state=present
    - name: Install libxslt-devel (pulls in libxml2-devel and libxslt)
      yum: name=libxslt-devel state=present

    # Still working out whether redhat scl is the least undesirable way to go here
    #- name: Get Python 2.7 Software Collection Repo (RHEL6 only)
    #  get_url: url=http://people.redhat.com/bkabrda/scl_python27.repo
    #            dest=/etc/yum.repos.d/scl_python27.repo
    #  when: ansible_os_family == "RedHat"

    # - name: Install python 2.7 from the SCR
    #  yum: name=python27 state=present
