# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# system packages to support the build and deployment of the wordspeak site
# Make sure python27.yml is run before this...
- hosts: vagrant
  sudo: yes
  sudo_user: root
  gather_facts: yes

  tasks:
    # NGINX stuff
    - name: Setup nginx staging.wordspeak.org config
      template: src=templates/nginx_confd_staging_wordspeak_org.j2
                 dest=/etc/nginx/conf.d/staging_wordspeak_org.conf
                 owner=root group=root mode=0644
    - name: Setup nginx www.wordspeak.org config
      template: src=templates/nginx_confd_www_wordspeak_org.j2
                 dest=/etc/nginx/conf.d/www_wordspeak_org.conf
                 owner=root group=root mode=0644

    - name: Copy ssl chained cert
      copy: src=/Users/esteele/Code/local/startssl/wordspeak.org.chained.crt
             dest=/etc/ssl/certs/wordspeak.org.chained.crt owner=root group=root mode=0644
    - name: Copy ssl trusted chained cert
      copy: src=/Users/esteele/Code/local/startssl/wordspeak.org.chained.trusted.crt
             dest=/etc/ssl/certs/wordspeak.org.chained.trusted.crt owner=root group=root mode=0644
    - name: Copy certificate key
      copy: src=/Users/esteele/Code/local/startssl/my-private-decrypted.key
             dest=/etc/ssl/certs/wordspeak.org.ssl.key owner=root group=root mode=0600
    
    # Need enchant 1.6 due to http://bugzilla.abisource.com/show_bug.cgi?id=12350 which is in 1.5 (RHEL6 default)
    # Use flexbox repo: http://sourceforge.net/projects/flexbox/files/
    # TODO Load key with rpm_key and enable gpg in repo conf
    - name: Install flexbox repo rpm
      yum: name=http://aarnet.dl.sourceforge.net/project/flexbox/flexbox-release-1-1.noarch.rpm
            state=present

    - name: Install java for yuicompressor
      yum: name=java-1.6.0-openjdk.x86_64 state=present
    - name: Install enchant for spell checking
      yum: name=enchant state=present
    - name: Install enchant-aspell for aspell compatibility
      yum: name=enchant-aspell state=present
    - name: Install GB English aspell dictionary
      yum: name=aspell-en state=present
    - name: Install libxslt-devel (pulls in libxml2-devel and libxslt)
      yum: name=libxslt-devel state=present

    - name: Setup staging.wordspeak.org parent directory
      file: path=/home/esteele/Sites/staging.wordspeak.org state=directory
             mode=0711 owner=esteele group=esteele

    - name: Setup www.wordspeak.org parent directory
      file: path=/home/esteele/Sites/www.wordspeak.org state=directory
             mode=0711 owner=esteele group=esteele

    - name: Create Nikola Cache directory
      file: path=/home/esteele/tmp/nikola_wordspeak_cache state=directory
             mode=0755 owner=esteele group=esteele

    - name: Create Nikola Output directory
      file: path=/home/esteele/tmp/nikola_wordspeak_output state=directory
             mode=0755 owner=esteele group=esteele

    # Just install something so that the venv gets created.
    - name: Install requests for nikola
      sudo: True
      sudo_user: esteele
      pip: name=requests virtualenv_command=/usr/local/bin/virtualenv-2.7 virtualenv=/home/esteele/.virtualenvs/wordspeak_n7 version=2.4.3

    # Git setup can't be done via ansible because of the private keys
    #- name: Checkout wordspeak repo
    #  git: repo=ssh://git@github.com/edwinsteele/wordspeak.org.git
    #        dest=/home/esteele/Code
    #- name: Checkout d3-projects submodule
    #  command: git submodule update --init chdir=/home/esteele/Code/wordspeak.org
    #            creates=/home/esteele/Code/wordspeak.org/files/d3-projects/.git
