# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# system packages to support the build and deployment of the wordspeak site
# Make sure python27.yml is run before this...
- hosts: all
  sudo: yes
  sudo_user: root
  gather_facts: yes

  tasks:
          
    - name: Setup ~esteele/Sites
      sudo: True
      sudo_user: esteele
      file: path=/home/esteele/Sites state=directory

    - name: Fix perms on ~esteele to allow ~/Sites to be served up
      sudo: True
      sudo_user: esteele
      file: path=/home/esteele state=directory mode=0711

    # NGINX stuff
    - name: Create nginx conf.d directory
      file: path=/etc/nginx/conf.d owner=root group=wheel mode=0755 state=directory

    - name: Setup nginx staging.wordspeak.org config
      template: src=templates/nginx_confd_staging_wordspeak_org.j2
                 dest=/etc/nginx/conf.d/staging_wordspeak_org.conf
                 owner=root group=wheel mode=0644
    - name: Setup nginx www.wordspeak.org config
      template: src=templates/nginx_confd_www_wordspeak_org.j2
                 dest=/etc/nginx/conf.d/www_wordspeak_org.conf
                 owner=root group=wheel mode=0644

    # Certs and keys already copied before, but repeating here means this is self-contained
    - name: Copy ssl chained cert
      copy: src=/Users/esteele/Code/local/startssl/wordspeak.org.chained.crt
             dest=/etc/ssl/certs/wordspeak.org.chained.crt owner=root group=wheel mode=0644
    - name: Copy ssl trusted chained cert
      copy: src=/Users/esteele/Code/local/startssl/wordspeak.org.chained.trusted.crt
             dest=/etc/ssl/certs/wordspeak.org.chained.trusted.crt owner=root group=wheel mode=0644
    - name: Copy certificate key
      copy: src=/Users/esteele/Code/local/startssl/www_wordspeak_org.key
             dest=/etc/ssl/certs/wordspeak.org.ssl.key owner=root group=wheel mode=0600
    
    - name: Create .ssh directory
      file: path=/home/esteele/.ssh owner=esteele group=esteele mode=0700 state=directory

    - name: Copy wordspeak deploy key
      copy: src=/Users/esteele/Code/local/sshkeys/github_wordspeak_deploy
             dest=/home/esteele/.ssh/github_wordspeak_deploy owner=esteele group=esteele mode=0600

    - name: Setup personal ssh config
      copy: src=templates/esteele_ssh_config
             dest=/home/esteele/.ssh/config owner=esteele group=esteele mode=0600

    - name: Install enchant for spell checking (OpenBSD)
      openbsd_pkg: name=enchant state=present
      environment:
          PKG_PATH: "{{PKG_PATH}}"
     
    # XXX Unclear whether this is necessary on OpenBSD
    - name: Install enchant-aspell for aspell compatibility
      yum: name=enchant-aspell state=present
      when: ansible_os_family == "RedHat"
    # XXX Unclear whether this is necessary on OpenBSD (perhaps en is in the base aspell package)
    - name: Install GB English aspell dictionary
      yum: name=aspell-en state=present
      when: ansible_os_family == "RedHat"
    - name: Install libxslt (OpenBSD)
      openbsd_pkg: name=libxslt state=present
      when: ansible_os_family == "OpenBSD"
      environment:
          PKG_PATH: "{{PKG_PATH}}"

    - name: Setup staging.wordspeak.org parent directory
      file: path=/var/www/htdocs/staging.wordspeak.org state=directory
             mode=0755 owner=esteele group=esteele

    - name: Setup staging.wordspeak.org symlink
      file: dest=/home/esteele/Sites/staging.wordspeak.org src=/var/www/htdocs/staging.wordspeak.org
             state=link

    - name: Setup www.wordspeak.org parent directory
      file: path=/var/www/htdocs/www.wordspeak.org state=directory
             mode=0755 owner=esteele group=esteele

    - name: Setup www.wordspeak.org symlink
      file: dest=/home/esteele/Sites/www.wordspeak.org src=/var/www/htdocs/www.wordspeak.org
             state=link

    - name: Create Nikola Cache directory
      file: path=/home/esteele/tmp/nikola_wordspeak_cache state=directory
             mode=0755 owner=esteele group=esteele

    - name: Create Nikola Output directory
      file: path=/home/esteele/tmp/nikola_wordspeak_output state=directory
             mode=0755 owner=esteele group=esteele

    # Just install something so that the venv gets created.
    - name: Install requests for nikola
      sudo: True
      sudo_user: esteele
      pip: name=requests virtualenv_command=/usr/local/bin/virtualenv-2.7 virtualenv=/home/esteele/.virtualenvs/wordspeak_n7 version=2.4.3

    # Git setup can't be done via ansible because of the private keys
    #- name: Checkout wordspeak repo
    #  git: repo=ssh://git@github.com/edwinsteele/wordspeak.org.git
    #        dest=/home/esteele/Code
    #- name: Checkout d3-projects submodule
    #  command: git submodule update --init chdir=/home/esteele/Code/wordspeak.org
    #            creates=/home/esteele/Code/wordspeak.org/files/d3-projects/.git
