---
# system packages to support the build and deployment of the wordspeak site
# Make sure python27.yml is run before this...
- hosts: vagrant
  user: root
  sudo: yes
  gather_facts: yes
  vars_files:
    - vars/defaults.yml

  tasks:
    # Need enchant 1.6 due to http://bugzilla.abisource.com/show_bug.cgi?id=12350 which is in 1.5 (RHEL6 default)
    # Use flexbox repo: http://sourceforge.net/projects/flexbox/files/
    - name: Install flexbox repo rpm
      yum: name=http://aarnet.dl.sourceforge.net/project/flexbox/flexbox-release-1-1.noarch.rpm
            state=present

    - name: Install xz for subsequent Linkchecker setup
      yum: name=xz state=present

    - name: Install enchant for spell checking
      yum: name=enchant state=present
    - name: Install enchant-aspell for aspell compatibility
      yum: name=enchant-aspell state=present
    - name: Install GB English aspell dictionary
      yum: name=aspell-en state=present
    - name: Install libxslt-devel (pulls in libxml2-devel and libxslt)
      yum: name=libxslt-devel state=present

